powerdata<-read.table("household_power_consumption.txt",sep=";",na.strings="?",stringsAsFactors=FALSE,dec=".",header=TRUE)
powerdata$Date<-as.Date(powerdata$Date,format="%d/%m/%Y")
date1<-as.Date("01/02/2007",format="%d/%m/%Y")
date2<-as.Date("02/02/2007",format="%d/%m/%Y")
powerdata<-subset(powerdata,date1<=Date&date2>=Date)

##Plot4
Global_active_power <- as.numeric(as.character(powerdata$Global_active_power))
dt <-paste(powerdata$Date, powerdata$Time)
dt <- as.POSIXct(dt)
Sub_metering_1<-as.numeric(as.character(powerdata$Sub_metering_1))
Sub_metering_2<-as.numeric(as.character(powerdata$Sub_metering_2))
Sub_metering_3<-as.numeric(as.character(powerdata$Sub_metering_3))
Global_reactive_power <- as.numeric(as.character(powerdata$Global_reactive_power))
Voltage <- as.numeric(as.character(powerdata$Voltage))
png("plot4.png", width=480, height=480)
par(mfrow=c(2,2))
plot(dt, Global_active_power, type = "l", xlab="",ylab = "Global Active Power")
plot(dt, Voltage, type = "l", xlab="datetime")
plot(dt, Sub_metering_1,col="black",type = "l", xlab="",ylab = "Energy sub metering")
lines(dt, Sub_metering_2, col="red",type = "l")
lines(dt, Sub_metering_3, col="blue",type = "l")
legend("topright", col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),lwd=1)
plot(dt, Global_reactive_power, type = "l", xlab="datetime")
dev.off()